---
apiVersion: kubeflow.org/v1alpha1
kind: TFJob
metadata:
  name: tfjob-gpu
spec:
  replicaSpecs:
  - template:
      spec:
        containers:
        - image: submod/gputest:latest
          name: tensorflow
          resources:
            limits:
              alpha.kubernetes.io/nvidia-gpu: 1
        restartPolicy: OnFailure
tfImage: submod/gputest:latest
